# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e157fc6e162aa68e472cdc141dcb2de3e6e9820be23f17b6e02b299aed5c65f4874a41a11ad32d19e92b45838e21119c6b811167ab3f1d4849ccfe3f6f40a32f

test:
  secret_key_base: 21e9ab7e158e640ea9723ffa81907e38bce49bffb102dc1d4d4c304cf0e0209061ed955d751958e05f353b65d087949e19ee7d0472c3401b713b58e19a57c255

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
